services:
  wazuh-manager:
    image: wazuh/wazuh-manager:4.14.1
    container_name: wazuh-manager
    hostname: wazuh-manager
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "55000:55000"
    volumes:
      - wazuh_data:/var/ossec/data

  wazuh-indexer:
    image: wazuh/wazuh-indexer:4.14.1
    container_name: wazuh-indexer
    hostname: wazuh-indexer
    environment:
      - cluster.name=wazuh-cluster
    ports:
      - "9200:9200"
    volumes:
      - indexer_data:/usr/share/wazuh-indexer/data

  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.14.1
    container_name: wazuh-dashboard
    hostname: wazuh-dashboard
    ports:
      - "5601:5601"
    depends_on:
      - wazuh-manager
      - wazuh-indexer

volumes:
  wazuh_data:
  indexer_data:

